import LegalPage from "@/components/LegalPage";

export const metadata = {
  title: "Terms of Service — Vault",
  description: "The plain-language terms for using Vault.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="26 August 2026">
      <h2>The short version</h2>
      <p>
        Vault is a personal knowledge hub. Your content is yours. Use the
        service reasonably, don&rsquo;t abuse it, and understand that it&rsquo;s
        early-stage software provided as-is. Using Vault means you accept
        these terms and the <a href="/privacy">Privacy Policy</a>.
      </p>

      <h2>Your content is yours</h2>
      <p>
        Everything you put into Vault — notes, tasks, files, finance entries —
        remains yours. You grant us only the narrow licence needed to operate
        the product: storing your data, syncing it between your devices, and
        processing it for features you invoke (search, AI answers, Google
        sync). We claim no other rights, and the licence ends when you delete
        the content or your account.
      </p>

      <h2>Your responsibilities</h2>
      <ul>
        <li>Keep your account credentials safe; you&rsquo;re responsible for
          activity under your account.</li>
        <li>Local-first cuts both ways: data that only lives in your browser
          is under your control <i>and</i> your care — use backups or sync
          for anything you can&rsquo;t afford to lose.</li>
        <li>Don&rsquo;t upload content you have no right to store, and don&rsquo;t use
          Vault for anything unlawful.</li>
        <li>Don&rsquo;t probe, overload or disrupt the service. Rate limits and
          storage quotas exist to keep it fair; working around them isn&rsquo;t
          allowed.</li>
      </ul>

      <h2>AI features</h2>
      <p>
        AI answers are generated by machine-learning models and can be wrong,
        incomplete or outdated — including finance-related summaries, which
        are informational and <b>not financial advice</b>. Review anything
        important before acting on it.
      </p>

      <h2>Third-party services</h2>
      <p>
        Some features rely on services with their own terms: Clerk (sign-in),
        AWS S3 (file storage), Neon &amp; Render (hosting), NVIDIA-hosted models
        (AI), and Google (Calendar/Drive/Docs, if you connect them). We&rsquo;re not
        responsible for those services, and a Google connection can be revoked
        any time from your Google account settings.
      </p>

      <h2>Early-stage software, no warranty</h2>
      <p>
        Vault is provided <b>&ldquo;as is&rdquo; and &ldquo;as available&rdquo;</b>, without
        warranties of any kind, express or implied. We work hard on
        reliability — including local-first storage precisely so an outage
        doesn&rsquo;t take your data — but we can&rsquo;t promise uninterrupted or
        error-free operation.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent the law allows, our total liability for any
        claim connected to Vault is limited to the amount you paid us for the
        service in the twelve months before the claim (currently: nothing, as
        Vault&rsquo;s core is free). We&rsquo;re not liable for indirect, incidental or
        consequential damages, or for loss of data you chose not to back up
        or sync.
      </p>

      <h2>Ending things</h2>
      <p>
        You can stop using Vault any time — export your data and delete your
        account from Settings. We may suspend or terminate accounts that
        violate these terms or endanger the service, and we&rsquo;ll be
        proportionate about it. If we ever discontinue the service, we&rsquo;ll
        give reasonable notice so you can export.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        If these terms change materially, the date above changes and the
        in-app link will point at the new version. Continued use after a
        change means the new version applies.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms:{" "}
        <a href="mailto:vikingrksk11@gmail.com">vikingrksk11@gmail.com</a>.
      </p>
    </LegalPage>
  );
}
