"""document text extraction

Revision ID: 5a6ac14158cf
Revises: 38de6bd1d7dd
Create Date: 2026-08-21 04:45:52.799518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy   # autogenerate emits Vector columns but never their import


# revision identifiers, used by Alembic.
revision: str = '5a6ac14158cf'
down_revision: Union[str, Sequence[str], None] = '38de6bd1d7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('items', sa.Column('extract_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'extract_error')
    op.drop_column('items', 'extracted_at')
    op.drop_column('items', 'extracted_text')
    # ### end Alembic commands ###
