"""index todos and kanban cards

Revision ID: a3b3a928718b
Revises: 5a6ac14158cf
Create Date: 2026-08-21 06:21:23.053008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy   # autogenerate emits Vector columns but never their import


# revision identifiers, used by Alembic.
revision: str = 'a3b3a928718b'
down_revision: Union[str, Sequence[str], None] = '5a6ac14158cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills the rows that already exist — a plain NOT NULL
    # add fails against any non-empty table, which autogenerate cannot know.
    # Dropped again afterwards so the default lives in the model, not the DB.
    op.add_column('embeddings', sa.Column('source_type', sa.String(length=12),
                                          nullable=False, server_default='item'))
    op.add_column('embeddings', sa.Column('source_ref', sa.String(length=64), nullable=True))
    op.add_column('embeddings', sa.Column('title', sa.Text(), nullable=True))
    op.alter_column('embeddings', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_embeddings_source_ref'), 'embeddings', ['source_ref'], unique=False)
    op.create_index(op.f('ix_embeddings_source_type'), 'embeddings', ['source_type'], unique=False)
    op.alter_column('embeddings', 'source_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_source_type'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_source_ref'), table_name='embeddings')
    op.alter_column('embeddings', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('embeddings', 'title')
    op.drop_column('embeddings', 'source_ref')
    op.drop_column('embeddings', 'source_type')
    # ### end Alembic commands ###
